version: '3.9'

services:
  postgres:
    image: postgres
    restart: on-failure
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB

    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
