"""empty message

Revision ID: a8cbe90c9e05
Revises: 305110289fc8
Create Date: 2023-10-27 22:17:55.316296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8cbe90c9e05'
down_revision: Union[str, None] = '305110289fc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('is_admin', sa.Boolean(), nullable=False))
    op.add_column('accounts', sa.Column('balance', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'balance')
    op.drop_column('accounts', 'is_admin')
    # ### end Alembic commands ###
